# 1) Numpy Arrays

## Array Basics

In [1]:
# 1D array

In [2]:
import numpy as np

In [3]:
my_list = [1,2,3,4,5]
print(my_list)

[1, 2, 3, 4, 5]


In [4]:
np.array(my_list)

array([1, 2, 3, 4, 5])

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3, 4, 5])

In [7]:
# 2D array

In [8]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## NumPy arrays using built in methods

In [11]:
import numpy as np

In [12]:
# 1) arange

In [13]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [15]:
# 2) zeros

In [16]:
np.zeros(3) # 1D array

array([0., 0., 0.])

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
# 3) ones

In [19]:
np.ones(4)

array([1., 1., 1., 1.])

In [20]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
# 4) linspace

In [22]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [23]:
np.linspace(0,5,15)

array([0.        , 0.35714286, 0.71428571, 1.07142857, 1.42857143,
       1.78571429, 2.14285714, 2.5       , 2.85714286, 3.21428571,
       3.57142857, 3.92857143, 4.28571429, 4.64285714, 5.        ])

In [24]:
# 5) eye

In [25]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
# 6) arrays of random numbers (uniform distribution between 0 to 1)

In [27]:
np.random.rand(5)

array([0.45861299, 0.67674751, 0.30568566, 0.06605908, 0.12851728])

In [28]:
np.random.rand(4,4)

array([[0.56655098, 0.56700078, 0.43167702, 0.7370199 ],
       [0.20901365, 0.04103604, 0.88736701, 0.63255047],
       [0.85442649, 0.70833847, 0.14345212, 0.46532567],
       [0.68333309, 0.40597032, 0.61316023, 0.989134  ]])

In [29]:
# 7) Standard normal distribution or gaussion distribution

In [30]:
np.random.randn(4) # 1D array

array([ 1.12368926, -0.65343292, -2.62011309, -0.34139518])

In [31]:
np.random.randn(4,5)

array([[ 0.81742355,  0.0054166 , -0.64151188, -0.25107122,  0.13989687],
       [-0.70139484,  0.28283606, -1.92314604, -1.51882671, -0.78788704],
       [ 0.56328588, -1.03296919, -0.73080452, -0.06204443, -0.54624995],
       [ 0.18736486, -0.98478089,  0.13446387,  0.0505671 , -0.05691231]])

In [32]:
# 8) randint

In [33]:
np.random.randint(0,100)

92

In [34]:
np.random.randint(0,100,10)

array([61, 84, 26, 44, 27, 95,  4, 53, 54, 13])

## Useful attributes and methods

In [35]:
arr = np.arange(25)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
# reshape method

In [38]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
arr.reshape(5,10)

ValueError: cannot reshape array of size 25 into shape (5,10)

In [40]:
# 2) max, min

In [41]:
ran_arr = np.random.randint(0,50,10)

In [42]:
ran_arr

array([47, 46, 23, 18, 17, 49, 16,  2, 43, 33])

In [43]:
ran_arr.max()

49

In [44]:
ran_arr.min()

2

In [45]:
ran_arr.argmax()

5

In [46]:
ran_arr.argmin()

7

In [47]:
# 3) shape

In [48]:
arr.shape

(25,)

In [49]:
b = arr.reshape(5,5)

In [50]:
b.shape

(5, 5)

In [51]:
# 4) dtype

In [52]:
arr.dtype

dtype('int32')

# 2) Numpy Indexing and Selection

## Indexing and Selection Basics

In [53]:
import numpy as np

In [54]:
arr = np.arange(10,21)

In [55]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [56]:
arr[5]

15

In [57]:
arr[0:5]

array([10, 11, 12, 13, 14])

In [58]:
arr[2:]

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [59]:
arr[:6]

array([10, 11, 12, 13, 14, 15])

## Broadcasting the values

In [60]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [61]:
arr[0:5] = 100

In [62]:
arr

array([100, 100, 100, 100, 100,  15,  16,  17,  18,  19,  20])

In [63]:
arr = np.arange(10,21)

In [64]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [65]:
slice_arr = arr[0:6]

In [66]:
slice_arr

array([10, 11, 12, 13, 14, 15])

In [67]:
slice_arr[:] = 99

In [68]:
slice_arr

array([99, 99, 99, 99, 99, 99])

In [69]:
arr

array([99, 99, 99, 99, 99, 99, 16, 17, 18, 19, 20])

In [70]:
arr_cp = arr.copy()

In [71]:
arr_cp

array([99, 99, 99, 99, 99, 99, 16, 17, 18, 19, 20])

In [72]:
arr[:] = 100

In [73]:
arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [74]:
arr_cp

array([99, 99, 99, 99, 99, 99, 16, 17, 18, 19, 20])

In [75]:
arr = np.arange(0,11)

In [76]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
slice_2 = arr[0:5]

In [78]:
slice_2

array([0, 1, 2, 3, 4])

In [79]:
slice_2[:] = 100

In [80]:
slice_2

array([100, 100, 100, 100, 100])

In [81]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [82]:
arr_cp2 = arr.copy()

In [83]:
arr_cp2[:] = 200

In [84]:
arr_cp2

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [85]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

## Indexing a 2D array(Matrix)

In [88]:
import numpy as np

In [89]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [90]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [91]:
arr_2d[0,0]

5

In [92]:
arr_2d[1,0]

20

In [93]:
arr_2d[0:2, 1:3]

array([[10, 15],
       [25, 30]])

## Conditional selection

In [94]:
arr = np.arange(0,11)

In [95]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [96]:
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [97]:
b = arr > 5

In [98]:
b

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [99]:
arr[b]

array([ 6,  7,  8,  9, 10])

In [100]:
arr[arr < 8]

array([0, 1, 2, 3, 4, 5, 6, 7])

# 3) Numpy Operations

In [101]:
import numpy as np

In [102]:
# array with array

In [103]:
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [104]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [105]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [106]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [107]:
arr / arr

C:\Users\rohit\AppData\Local\Temp/ipykernel_12124/3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [108]:
# array with sclar

In [109]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [110]:
arr - 50

array([-50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40])

In [111]:
arr *2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [112]:
arr/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [113]:
1/0

ZeroDivisionError: division by zero

In [114]:
1/arr

C:\Users\rohit\AppData\Local\Temp/ipykernel_12124/255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [115]:
arr**3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [116]:
# universal array functions

In [117]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [118]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [119]:
np.max(arr)

10

In [120]:
np.min(arr)

0

In [121]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [122]:
np.log(arr)

C:\Users\rohit\AppData\Local\Temp/ipykernel_12124/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])